---
title: 'Introduction'
teaching: 20
exercises: 10
---

:::::::::::::::::::::::::::::::::::::: questions


- Introduces the basics of the photogrammetry technique, and its applications
in Cultural Heritage.

:::::::::::::::::::::::::::::::::::::::::::::::::



Photogrammetry is a techniques also known as Structure from Motion (SfM). 

They are both used to refer to the computing process 
of estimating the 3D structure of a scene from a set of 2D raster images.
The technique receives as an **input** a set of raster images of an object or
environments, and **outputs** a 3D model.


The underlying technology is more familiar that you might think! 

It is based on the same principles that the ones use by our
vision system to perceive the 3-dimensional world.

![Bernard de Go Mars under Public Domain &copy; from [Wikimedia] (https://commons.wikimedia.org/w/index.php?curid=25846)](fig/Yokohama4MaidsChrysanthemum.jpg){alt="two views" width="60%"}

![Bernard de Go Mars under Public Domain &copy; from [Wikimedia] (https://commons.wikimedia.org/w/index.php?curid=25846)](fig/Yokohama4MaidsChrysanthemumWikiAnim.gif){alt="two views animated" width="60%"}

Because of this, analogue photographers in the 19th century were already producing stereoscopic and photogrammetry
set of images of many subjects[^1].

[^1]: [Jörg Albertz (2001) Albrecht Meydenbauer – Pioneer Of Photogrammetric Documentation Of The Cultural Heritage. Proceedings 18th International Symposium CIPA 2001](http://www.theulegium.de/fileadmin/user_upload/Texte/Meydenb.pdf ) 


Moreover, the there is no restriction on the 
scale that photogrammetry operates.

As such, photogrammtry is performed 
at a variety of ranges, from microscopic images
to aerial or space images.


## Heritage Applications 

Photogrammetry is an accessible technique
for recording information
related to the 3D surface and colour of 
heritage objects and environments.

**Be aware** that it does not mean
it can be applied to every object.
There are some restrictions for deploying
this technique. For instance, it 
does not work well with transparent
or reflective, shiny objects. Neither
does it work well with objects that move
constantly, like a live animal or a dress
worn by someone.

While photogrammetry may not be ideal for reflective, 
transparent, and moving objects, there are other 
Sometimes, this includes coating an object
with sprays, or accessing specialised dome-shape equipment
that captures the interaction of light with an object
so that this can be replicated in the 3D model.

It can be easily deployed with
basic equipment, including **digital cameras**
and there isa variety of software raning
from *free* to *professional with costly fees*.
So it scales to various budgets.

Hence, it can be deployed for research, but 
also for archiving and allowing
wider access.


## Archaeological sites
<iframe onload="this.width=screen.width/2;this.height=screen.height/2;" title="Skara Brae, Orkney" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share src="https://sketchfab.com/models/db877d56cfd4441a8bc844419790f50a/embed"> </iframe> 

<p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/skara-brae-orkney-db877d56cfd4441a8bc844419790f50a?utm_medium=embed&utm_campaign=share-popup&utm_content=db877d56cfd4441a8bc844419790f50a" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> Skara Brae, Orkney </a> by <a href="https://sketchfab.com/HistoricEnvironmentScotland?utm_medium=embed&utm_campaign=share-popup&utm_content=db877d56cfd4441a8bc844419790f50a" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> Historic Environment Scotland </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=db877d56cfd4441a8bc844419790f50a" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p>

## Museum artefacts
<iframe onload="this.width=screen.width/2;this.height=screen.height/2;" title="Egyptian Boat" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share src="https://sketchfab.com/models/fb9d37ed48644f5eae23e303e4a3ada0/embed"> </iframe> 

<p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/egyptian-boat-fb9d37ed48644f5eae23e303e4a3ada0?utm_medium=embed&utm_campaign=share-popup&utm_content=fb9d37ed48644f5eae23e303e4a3ada0" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> Egyptian Boat </a> by <a href="https://sketchfab.com/britishmuseum?utm_medium=embed&utm_campaign=share-popup&utm_content=fb9d37ed48644f5eae23e303e4a3ada0" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> The British Museum </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=fb9d37ed48644f5eae23e303e4a3ada0" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p>



## Architecture 
<iframe onload="this.width=screen.width/2;this.height=screen.height/2;" title="Kuelap - Construcción" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share src="https://sketchfab.com/models/467d4c2e221a449bb112af64c57fa248/embed"> </iframe> 

<p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/kuelap-construccion-467d4c2e221a449bb112af64c57fa248?utm_medium=embed&utm_campaign=share-popup&utm_content=467d4c2e221a449bb112af64c57fa248" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> Kuelap - Construcción </a> by <a href="https://sketchfab.com/MinisteriodeCulturaPeru?utm_medium=embed&utm_campaign=share-popup&utm_content=467d4c2e221a449bb112af64c57fa248" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> Ministerio de Cultura Perú </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=467d4c2e221a449bb112af64c57fa248" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p>

## Natural history 
<iframe onload="this.width=screen.width/2;this.height=screen.height/2;" title="Southern Toad (UF Herp 8849)" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share src="https://sketchfab.com/models/b43cdd6bda094cbd9f748cfd6f83992d/embed"> </iframe> 

<p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/southern-toad-uf-herp-8849-b43cdd6bda094cbd9f748cfd6f83992d?utm_medium=embed&utm_campaign=share-popup&utm_content=b43cdd6bda094cbd9f748cfd6f83992d" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> Southern Toad (UF Herp 8849) </a> by <a href="https://sketchfab.com/FloridaMuseum?utm_medium=embed&utm_campaign=share-popup&utm_content=b43cdd6bda094cbd9f748cfd6f83992d" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> FloridaMuseum </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=b43cdd6bda094cbd9f748cfd6f83992d" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p>

## Textiles
<iframe onload="this.width=screen.width/2;this.height=screen.height/2;" title="Pink and green Spanish dress" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share src="https://sketchfab.com/models/a11eb33d129a47a4a837cd2b4d232502/embed"> </iframe> 

<p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/pink-and-green-spanish-dress-a11eb33d129a47a4a837cd2b4d232502?utm_medium=embed&utm_campaign=share-popup&utm_content=a11eb33d129a47a4a837cd2b4d232502" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> Pink and green Spanish dress </a> by <a href="https://sketchfab.com/santacruzmah?utm_medium=embed&utm_campaign=share-popup&utm_content=a11eb33d129a47a4a837cd2b4d232502" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> Santa Cruz Museum of Art and History </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=a11eb33d129a47a4a837cd2b4d232502" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p>




:::: challenge

List the objects and environments which
are relevant to your own projects.

Search in [SketchFab](Sketchfab) whether 
3D models of these objects are available. 


Reflect which might
be suitable to test with photogrammetry.


::::
