---
title: 'Using the software'
teaching: 10
exercises: 2
---

## Using the software
Once the photographs have been acquired, the next step is to transfer the images to a PC (we tested the protocol with a PC with 16GB RAM). 

You should have access to photogrammetry software including: 

- Photoscan and image processing software (e.g. Photoshop, Gimp) if you wish to post- process the images.

- Whatever processing you apply to images (e.g. brightness, colour adjustments) should be applied to the whole dataset. Otherwise you will have alignment problems. Resizing, rotating and transforming the geometry of the images shouldn’t be applied.




5. Useful resources and extra reading
- Images and content from James Hays, Computer Vision module @ Brown University: http://cs.brown.edu/courses/cs143/
- 	www.stporter.com/wp- content/uploads/2016/04/A_Comparison_of_Methods_for_Creating_3D.pdf
- 	http://www.agisoft.com/support/tips-tricks/
- https://blog.sketchfab.com/how-to-set-up-a-successful-photogrammetry-project/
- 	http://www.tested.com/art/makers/460142-art-photogrammetry-how-take-your- photos/
